colbuild package="" *cmake_flags:
    @if [ ! -d "src" ] || [ -f "package.xml" ] || [ -f "CMakeLists.txt" ]; then \
        echo "Error: colbuild must be run from the workspace root (where 'src' exists, but not 'package.xml')."; \
        exit 1; \
    fi
    colcon build --symlink-install \
        --event-handlers=console_cohesion+ \
        {{ if package != "" { "--packages-up-to " + package } else { "" } }} \
        --cmake-args -GNinja -Wno-deprecated \
        -DCMAKE_POLICY_DEFAULT_CMP0144=NEW \
        -DCMAKE_POLICY_DEFAULT_CMP0144=NEW \
        -DCMAKE_POLICY_DEFAULT_CMP0167=NEW \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_INSTALL_MESSAGE=LAZY \
        {{ cmake_flags }}
