let g:pathogen_disabled = []
if v:version < '801'
    call add(g:pathogen_disabled, 'YouCompleteMe')
endif

runtime! bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

syntax on
set encoding=utf-8
set number
set noswapfile
set hlsearch
set ignorecase
set incsearch
autocmd FileType c,cpp,h,hpp set ts=2 sw=2 softtabstop=2 expandtab

autocmd FileType c,cpp,h,hpp setlocal equalprg=clang-format
set tabstop=4 shiftwidth=4 softtabstop=4 expandtab
set backspace=indent,eol,start

nnoremap ; :

"reload the .vimrc
nmap <silent> <leader>rv :source ~/.vimrc<CR>
"show spaces"
nmap <silent> <leader>s :set nolist!<CR>
"show line numbers"
nmap <silent> <leader>l :set nonu!<CR>
"wrap lines"
nmap <silent> <leader>w :set nowrap!<CR>
"hide hightlight of searches"
nmap <silent> // :nohlsearch<CR>

" Movements shortcuts {{{

" tmux-style moving between buffers
map <C-a><Left> <C-w>h
map <C-a><Down> <C-w>j
map <C-a><Up> <C-w>k
map <C-a><Right> <C-w>l

" Buffer switching/management, might as well use those keys for something useful
map <Right> :bnext<CR>
imap <Right> <ESC>:bnext<CR>
map <Left> :bprev<CR>
imap <Left> <ESC>:bprev<CR>
" Maximize only this window"
nmap <silent> <leader>m :only<CR>
"vertical split"
nmap <silent> <leader>v :bel :vne<CR>
"horizontal split"
nmap <silent> <leader>f :bel :new<CR>
"close viewport buffer"
nmap <silent> <leader>x :hid<CR>
" }}}

" Edit the .bashrc"
nmap <silent> <leader>eb :e ~/.bashrc<CR>
" Edit the .zshrc"
nmap <silent> <leader>ez :e ~/.zshrc<CR>
" Edit the .vimrc"
nmap <silent> <leader>ev :e ~/.vimrc<CR>
" Edit the .gitconfig"
nmap <silent> <leader>eg :e ~/.gitconfig<CR>
" Edit the .tmux.conf"
nmap <silent> <leader>et :e ~/.tmux.conf<CR>

filetype plugin indent on

au FileType python setlocal formatprg=autopep8\ -

highlight Pmenu ctermfg=15 ctermbg=0 guifg=#ffffff guibg=#000000
let &t_TI = ""
let &t_TE = ""

let g:airline_powerline_fonts = 1
let g:airline_theme='molokai'

let g:ycm_autoclose_preview_window_after_insertion = 1
" Let clangd fully control code completion
let g:ycm_clangd_uses_ycmd_caching = 0
" Use installed clangd, not YCM-bundled clangd which doesn't get updates.
let g:ycm_clangd_binary_path = exepath("/home/hs293go/.config/Code/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/13.0.0/clangd_13.0.0/bin/clangd")

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

